name: Deploy to GitHub Pages
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: planwithus-${{ github.sha }}
          path: build/

  deploy-gh-pages:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: planwithus-${{ github.sha }}
          path: build/
      - run: touch build/.nojekyll

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build
          git-config-name: GitHub Actions
          git-config-email: 813865+bnjmnt4n@users.noreply.github.com
